In [3]:
import tensorflow as tf
import numpy as np

In [5]:
%tensorflow_version 2.x
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [7]:
with tf.device('/device:GPU:0'):
  xy_train = np.loadtxt('/content/sample_data/mnist_train_small.csv', delimiter=',', dtype=np.float32)
  x_train = xy_train[:, 1:]
  y_train = xy_train[:, 0]

  print(x_train, "\nx_train shape:", x_train.shape)
  print(y_train, "\ny_train shape:", y_train.shape)

  nb_classes = 10 # 0 ~ 9
  y_train_one_hot = tf.keras.utils.to_categorical(y_train, nb_classes)
  print("one_hot:", y_train_one_hot)


  tf.model = tf.keras.Sequential()
  tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=784, activation="softmax"))
  tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
  tf.model.summary()

  history = tf.model.fit(x_train, y_train_one_hot, epochs=100)

  xy_test = np.loadtxt('/content/sample_data/mnist_test.csv', delimiter=',', dtype=np.float32)
  x_test = xy_test[:, 1:]
  y_test = xy_test[:, 0]

  pred = tf.keras.backend.eval(tf.argmax(tf.model.predict(x_test), axis=1))
  for p, y in zip(pred, y_test): # this case don't need flatten()
      print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 
x_train shape: (20000, 784)
[6. 5. 7. ... 2. 9. 5.] 
y_train shape: (20000,)
one_hot: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[True] Prediction: 3 True Y: 3
[True] Prediction: 9 True Y: 9
[True] Prediction: 9 True Y: 9
[True] Prediction: 8 True Y: 8
[True] Prediction: 4 True Y: 4
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 6 True Y: 6
[True] Prediction: 0 True Y: 0
[True] Prediction: 9 True Y: 9
[True] Prediction: 6 True Y: 6
[True] Prediction: 8 True Y: 8
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[False] Prediction: 4 True Y: 9
[True] Prediction: 8 True Y: 8
[False] Prediction: 4 True Y: 9
[True] Prediction: 2 True Y: 2
[True] Prediction: 3 True Y: 3
[True] Prediction: 5 True Y: 5
[True] Prediction: 5 True Y: 5
[True] Prediction: 9 True Y: 9
[True] Prediction: 4 True Y: 4
[False] Prediction: 3 True Y: 2
[True] Prediction: 1 True Y: 1
[True] Prediction: 9 True Y: 9
[True] Prediction: 4 True Y: 4
[True] Prediction: 3 True Y: 3
[True] Prediction: 9 True Y: 9
[True] Prediction: 6 True Y: 6
